sudo: required
dist: trusty
language: node_js

node_js:
  - "7"

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
install:
  - npm install

script:
  - ng build --prod --base-href https://aaradhanas.github.io/showdown-editor/
  - ng lint
  - ng test --watch=false --code-coverage
  - ng e2e
  - cd dist
  
after_success:
  - codecov

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
